/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Geral
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Valores = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modelo Calculadora");

        Valores.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(0, 4, 4, 6));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geral\\Downloads\\icons8-percentagem-24.png")); // NOI18N
        jPanel1.add(jButton1);

        jButton3.setText("CE");
        jPanel1.add(jButton3);

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geral\\Downloads\\icons8-c-minúsculo-26.png")); // NOI18N
        jPanel1.add(jButton5);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geral\\Downloads\\icons8-sinal-de-igual-24.png")); // NOI18N
        jPanel1.add(jButton2);

        jButton4.setText("1/X");
        jPanel1.add(jButton4);

        jButton6.setText("X²");
        jPanel1.add(jButton6);

        jButton7.setText("2√X");
        jPanel1.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geral\\Downloads\\icons8-dividisão-30.png")); // NOI18N
        jPanel1.add(jButton8);

        jButton9.setText("7");
        jPanel1.add(jButton9);

        jButton10.setText("8");
        jPanel1.add(jButton10);

        jButton11.setText("9");
        jPanel1.add(jButton11);

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geral\\Downloads\\icons8-multiplicação-30.png")); // NOI18N
        jPanel1.add(jButton12);

        jButton13.setText("4");
        jPanel1.add(jButton13);

        jButton14.setText("5");
        jPanel1.add(jButton14);

        jButton15.setText("6");
        jPanel1.add(jButton15);

        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geral\\Downloads\\icons8-subtração-30.png")); // NOI18N
        jPanel1.add(jButton16);

        jButton17.setText("1");
        jPanel1.add(jButton17);

        jButton18.setText("2");
        jPanel1.add(jButton18);

        jButton19.setText("3");
        jPanel1.add(jButton19);

        jButton20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geral\\Downloads\\icons8-soma-30.png")); // NOI18N
        jPanel1.add(jButton20);

        jButton21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geral\\Downloads\\icons8-mais-e-menos-30.png")); // NOI18N
        jPanel1.add(jButton21);

        jButton22.setText("0");
        jPanel1.add(jButton22);

        jButton23.setText(",");
        jPanel1.add(jButton23);

        jButton24.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geral\\Downloads\\icons8-sinal-de-igual-24.png")); // NOI18N
        jPanel1.add(jButton24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Valores)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Valores, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Valores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
